version: '3.8'

services:
  auth-db:
    image: postgres:15-alpine
    container_name: auth_db_container
    restart: always
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_password
      POSTGRES_DB: auth_db
    ports:
      - "5433:5432"
    volumes:
      - ./services/auth-service/init.sql:/docker-entrypoint-initdb.d/init.sql
      - auth_db_data:/var/lib/postgresql/data

  auth-service:
    build: ./services/auth-service
    container_name: auth_service_container
    restart: always
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgres://auth_user:auth_password@auth-db:5432/auth_db
      JWT_SECRET: anirudh123
      JWT_EXPIRES_IN: 1h
      PORT: 5000
    depends_on:
      - auth-db

  vendor-db:
    image: postgres:15-alpine
    container_name: vendor_db_container
    restart: always
    environment:
      POSTGRES_USER: vendor_user
      POSTGRES_PASSWORD: vendor_password
      POSTGRES_DB: vendor_db
    ports:
      - "5434:5432"
    volumes:
      - ./services/vendor-service/init.sql:/docker-entrypoint-initdb.d/init.sql
      - vendor_db_data:/var/lib/postgresql/data

  vendor-service:
    build: ./services/vendor-service
    container_name: vendor_service_container
    restart: always
    ports:
      - "5001:5001"
    environment:
      DATABASE_URL: postgres://vendor_user:vendor_password@vendor-db:5432/vendor_db
      JWT_SECRET: anirudh123
      PORT: 5001
    depends_on:
      - vendor-db

  nginx:
    image: nginx:alpine
    container_name: api_gateway
    ports:
      - "8080:80"
    # 8080 is host port and 80 is container port
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - auth-service
      - vendor-service


volumes:
  auth_db_data:
  vendor_db_data:
