version: "3.8"

services:

  # -----------------------------
  # AUTH SERVICE
  # -----------------------------
  auth-db:
    image: postgres:15-alpine
    container_name: auth_db_container
    restart: always
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_password
      POSTGRES_DB: auth_db
    ports:
      - "5433:5432"
    volumes:
      - ./services/auth-service/init.sql:/docker-entrypoint-initdb.d/init.sql
      - auth_db_data:/var/lib/postgresql/data

  auth-service:
    build: ./services/auth-service
    container_name: auth_service_container
    restart: always
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgres://auth_user:auth_password@auth-db:5432/auth_db
      JWT_SECRET: anirudh123
      JWT_EXPIRES_IN: 1h
      PORT: 5000
    depends_on:
      - auth-db


  # -----------------------------
  # VENDOR SERVICE
  # -----------------------------
  vendor-db:
    image: postgres:15-alpine
    container_name: vendor_db_container
    restart: always
    environment:
      POSTGRES_USER: vendor_user
      POSTGRES_PASSWORD: vendor_password
      POSTGRES_DB: vendor_db
    ports:
      - "5434:5432"
    volumes:
      - ./services/vendor-service/init.sql:/docker-entrypoint-initdb.d/init.sql
      - vendor_db_data:/var/lib/postgresql/data

  vendor-service:
    build: ./services/vendor-service
    container_name: vendor_service_container
    restart: always
    ports:
      - "5001:5001"
    environment:
      DATABASE_URL: postgres://vendor_user:vendor_password@vendor-db:5432/vendor_db
      JWT_SECRET: anirudh123
      PORT: 5001
    depends_on:
      - vendor-db


  # -----------------------------
  # ORDER SERVICE
  # -----------------------------
  order-db:
    image: postgres:15-alpine
    container_name: order_db_container
    restart: always
    environment:
      POSTGRES_USER: order_user
      POSTGRES_PASSWORD: order_password
      POSTGRES_DB: order_db
    ports:
      - "5435:5432"
    volumes:
      - ./services/order-service/init.sql:/docker-entrypoint-initdb.d/init.sql
      - order_db_data:/var/lib/postgresql/data

  order-service:
    build: ./services/order-service
    container_name: order_service_container
    restart: always
    ports:
      - "5002:5002"
    environment:
      DATABASE_URL: postgres://order_user:order_password@order-db:5432/order_db
      JWT_SECRET: anirudh123
      PORT: 5002
      RABBITMQ_URL: amqp://rabbitmq
      REDIS_HOST: redis
    depends_on:
      - order-db
      - rabbitmq
      - redis


  # -----------------------------
  # DELIVERY SERVICE
  # -----------------------------
  # delivery-db:
  #   image: postgres:15-alpine
  #   container_name: delivery_db_container
  #   restart: always
  #   environment:
  #     POSTGRES_USER: delivery_user
  #     POSTGRES_PASSWORD: delivery_password
  #     POSTGRES_DB: delivery_db
  #   ports:
  #     - "5436:5432"
  #   volumes:
  #     - ./services/delivery-service/init.sql:/docker-entrypoint-initdb.d/init.sql
  #     - delivery_db_data:/var/lib/postgresql/data

  # delivery-service:
  #   build: ./services/delivery-service
  #   container_name: delivery_service_container
  #   restart: always
  #   ports:
  #     - "5003:5003"
  #   environment:
  #     DATABASE_URL: postgres://delivery_user:delivery_password@delivery-db:5432/delivery_db
  #     JWT_SECRET: anirudh123
  #     PORT: 5003
  #     RABBITMQ_URL: amqp://rabbitmq
  #   depends_on:
  #     - delivery-db
  #     - rabbitmq


  # -----------------------------
  # RABBITMQ
  # -----------------------------
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_container
    ports:
      - "5672:5672"
      - "15672:15672"  # management UI
    restart: always


  # -----------------------------
  # REDIS
  # -----------------------------
  redis:
    image: redis:7-alpine
    container_name: redis_container
    ports:
      - "6379:6379"
    restart: always


  # -----------------------------
  # NGINX API GATEWAY
  # -----------------------------
  nginx:
    image: nginx:alpine
    container_name: api_gateway
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - auth-service
      - vendor-service
      - order-service

volumes:
  auth_db_data:
  vendor_db_data:
  order_db_data:
